# Generated by Django 4.0.4 on 2022-05-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_books_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookproducts',
            name='summary',
            field=models.TextField(default='This is cool!'),
        ),
    ]
