# Generated by Django 4.0.4 on 2022-05-14 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_books_page', '0003_alter_bookproducts_price_alter_bookproducts_summary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookproducts',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookproducts',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
